import Head from "next/head";
import Image from "next/image";
import Students from "../components/Students";
import styles from "../styles/Home.module.css";

export default function Home({ studentInfo }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Students studentInfo={studentInfo} />
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://api.hatchways.io/assessment/students");
  const studentInfo = await res.json();
  console.log(studentInfo);
  return {
    props: {
      studentInfo,
    },
  };
}
